<?php
// Plugin definition
$plugin = array(
  'title' => t('Homly'),
  'icon' => 'homly.png',
  'category' => t('Panopoly'),
  'theme' => 'homly',
  'css' => 'homly.css',
  'regions' => array(
    'headertop' => t('Header Top'),
    'headerfirst' => t('Header First'),
    'headersecond' => t('Header Second'),
    'columntop' => t('Column Top'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'column3' => t('Third Column'),
    'postcolumntop' => t('Post Top Column'),
    'postcolumn1' => t('Post First Column'),
    'postcolumn2' => t('Post Second Column'),
    'postcolumn3' => t('Post Third Column'),
    'footercolumntop' => t('Footer Top Column'),
    'footercolumn1' => t('Footer First Column'),
    'footercolumn2' => t('Footer Second Column'),
    'footercolumn3' => t('Footer Third Column'),
  ),
);
