<?php
// Plugin definition
$plugin = array(
  'title' => t('Harrison'),
  'icon' => 'harrison.png',
  'category' => t('Panopoly'),
  'theme' => 'harrison',
  'css' => 'harrison.css',
  'regions' => array(
    'header' => t('Header'),
    'middle_first' => t('Middle First'),
    'middle_second' => t('Middle Second'),
    'middle_third' => t('Middle Third'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'footer' => t('Footer'),
  ),
);
