<?php
// Plugin definition
$plugin = array(
  'title' => t('Harris Advanced'),
  'icon' => 'harris-advanced.png',
  'category' => t('Panopoly'),
  'theme' => 'harris_advanced',
  'css' => 'harris-advanced.css',
  'regions' => array(
    'header' => t('Header'),
    'middle_first' => t('Middle First'),
    'middle_second' => t('Middle Second'),
    'middle_third' => t('Middle Third'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'contentmain' => t('Content'),
    'footer' => t('Footer'),
  ),
);
